//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.08 at 12:02:29 AM CET 
//


package Zahtev.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CTPodaciOZahtevu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTPodaciOZahtevu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Mesto">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;pattern value="[A-Z][A-Za-z ]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Trazioc" type="{http://www.ftn.uns.ac.rs/zahtev}CTLice"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTPodaciOZahtevu", propOrder = {
    "mesto",
    "datum",
    "trazioc"
})
public class CTPodaciOZahtevu {

    @XmlElement(name = "Mesto", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
    protected String mesto;
    @XmlElement(name = "Datum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(name = "Trazioc", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
    protected CTLice trazioc;

    @Override
    public String toString() {
        return "CTPodaciOZahtevu {\n" +
                "\t\t\t\t\tmesto = " + mesto + ",\n" +
                "\t\t\t\t\tdatum = " + datum.toString() + ",\n" +
                "\t\t\t\t\ttrazioc = " + trazioc.getIme() + " " + trazioc.getPrezime() + "\n" +
                "\t\t\t\t\t}";
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the trazioc property.
     * 
     * @return
     *     possible object is
     *     {@link CTLice }
     *     
     */
    public CTLice getTrazioc() {
        return trazioc;
    }

    /**
     * Sets the value of the trazioc property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTLice }
     *     
     */
    public void setTrazioc(CTLice value) {
        this.trazioc = value;
    }

}
