//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.08 at 12:02:29 AM CET 
//


package Zahtev.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTSadrzaj complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTSadrzaj">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Telo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Paragraf">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Zakon" type="{http://www.ftn.uns.ac.rs/zahtev}CTZakon"/>
 *                             &lt;element name="SluzbeniGlasnik" type="{http://www.ftn.uns.ac.rs/zahtev}CTSluzbeniGlasnik"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="IzboriZahteva" type="{http://www.ftn.uns.ac.rs/zahtev}CTIzboriZahteva"/>
 *                   &lt;element name="Informacije">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PodaciOZahtevu" type="{http://www.ftn.uns.ac.rs/zahtev}CTPodaciOZahtevu"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTSadrzaj", propOrder = {
    "naslov",
    "telo"
})
public class CTSadrzaj {

    @XmlElement(name = "Naslov", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
    protected String naslov;
    @XmlElement(name = "Telo", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
    protected CTSadrzaj.Telo telo;

    @Override
    public String toString() {
        return "CTSadrzaj {\n" +
                "\t\tnaslov = " + naslov + ",\n" +
                "\t\ttelo = " + telo + "\n" +
                "\t\t}";
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the telo property.
     * 
     * @return
     *     possible object is
     *     {@link CTSadrzaj.Telo }
     *     
     */
    public CTSadrzaj.Telo getTelo() {
        return telo;
    }

    /**
     * Sets the value of the telo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTSadrzaj.Telo }
     *     
     */
    public void setTelo(CTSadrzaj.Telo value) {
        this.telo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Paragraf">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Zakon" type="{http://www.ftn.uns.ac.rs/zahtev}CTZakon"/>
     *                   &lt;element name="SluzbeniGlasnik" type="{http://www.ftn.uns.ac.rs/zahtev}CTSluzbeniGlasnik"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="IzboriZahteva" type="{http://www.ftn.uns.ac.rs/zahtev}CTIzboriZahteva"/>
     *         &lt;element name="Informacije">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PodaciOZahtevu" type="{http://www.ftn.uns.ac.rs/zahtev}CTPodaciOZahtevu"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paragraf",
        "izboriZahteva",
        "informacije",
        "podaciOZahtevu"
    })
    public static class Telo {

        @XmlElement(name = "Paragraf", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
        protected CTSadrzaj.Telo.Paragraf paragraf;
        @XmlElement(name = "IzboriZahteva", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
        protected CTIzboriZahteva izboriZahteva;
        @XmlElement(name = "Informacije", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
        protected String informacije;
        @XmlElement(name = "PodaciOZahtevu", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
        protected CTPodaciOZahtevu podaciOZahtevu;

        @Override
        public String toString() {
            return "Telo {\n" +
                    "\t\t\t\tparagraf = " + paragraf + ",\n" +
                    "\t\t\t\tizboriZahteva = " + izboriZahteva + ",\n" +
                    "\t\t\t\tinformacije = " + informacije + ",\n" +
                    "\t\t\t\tpodaciOZahtevu = " + podaciOZahtevu + "\n" +
                    "\t\t\t\t}";
        }

        /**
         * Gets the value of the paragraf property.
         * 
         * @return
         *     possible object is
         *     {@link CTSadrzaj.Telo.Paragraf }
         *     
         */
        public CTSadrzaj.Telo.Paragraf getParagraf() {
            return paragraf;
        }

        /**
         * Sets the value of the paragraf property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTSadrzaj.Telo.Paragraf }
         *     
         */
        public void setParagraf(CTSadrzaj.Telo.Paragraf value) {
            this.paragraf = value;
        }

        /**
         * Gets the value of the izboriZahteva property.
         * 
         * @return
         *     possible object is
         *     {@link CTIzboriZahteva }
         *     
         */
        public CTIzboriZahteva getIzboriZahteva() {
            return izboriZahteva;
        }

        /**
         * Sets the value of the izboriZahteva property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTIzboriZahteva }
         *     
         */
        public void setIzboriZahteva(CTIzboriZahteva value) {
            this.izboriZahteva = value;
        }

        /**
         * Gets the value of the informacije property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInformacije() {
            return informacije;
        }

        /**
         * Sets the value of the informacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInformacije(String value) {
            this.informacije = value;
        }

        /**
         * Gets the value of the podaciOZahtevu property.
         * 
         * @return
         *     possible object is
         *     {@link CTPodaciOZahtevu }
         *     
         */
        public CTPodaciOZahtevu getPodaciOZahtevu() {
            return podaciOZahtevu;
        }

        /**
         * Sets the value of the podaciOZahtevu property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTPodaciOZahtevu }
         *     
         */
        public void setPodaciOZahtevu(CTPodaciOZahtevu value) {
            this.podaciOZahtevu = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Zakon" type="{http://www.ftn.uns.ac.rs/zahtev}CTZakon"/>
         *         &lt;element name="SluzbeniGlasnik" type="{http://www.ftn.uns.ac.rs/zahtev}CTSluzbeniGlasnik"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "zakon",
            "sluzbeniGlasnik"
        })
        public static class Paragraf {

            @XmlElement(name = "Zakon", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
            protected CTZakon zakon;
            @XmlElement(name = "SluzbeniGlasnik", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
            protected CTSluzbeniGlasnik sluzbeniGlasnik;

            @Override
            public String toString() {
                StringBuilder builder = new StringBuilder();
                for (String broj : sluzbeniGlasnik.getBrojevi().getBroj()) {
                    builder.append(broj);
                    builder.append(", ");
                }
                String brojeviString = builder.toString();
                return "Paragraf {\n" +
                        "\t\t\t\t\tzakon = " + zakon.getNaziv() + ", clan = " + zakon.getClan() + ", stav = " + zakon.getStav() + ",\n" +
                        "\t\t\t\t\tsluzbeniGlasnik = " + sluzbeniGlasnik.getNaziv() + ", brojevi = " + brojeviString + "\n" +
                        "\t\t\t\t\t}";
            }

            /**
             * Gets the value of the zakon property.
             * 
             * @return
             *     possible object is
             *     {@link CTZakon }
             *     
             */
            public CTZakon getZakon() {
                return zakon;
            }

            /**
             * Sets the value of the zakon property.
             * 
             * @param value
             *     allowed object is
             *     {@link CTZakon }
             *     
             */
            public void setZakon(CTZakon value) {
                this.zakon = value;
            }

            /**
             * Gets the value of the sluzbeniGlasnik property.
             * 
             * @return
             *     possible object is
             *     {@link CTSluzbeniGlasnik }
             *     
             */
            public CTSluzbeniGlasnik getSluzbeniGlasnik() {
                return sluzbeniGlasnik;
            }

            /**
             * Sets the value of the sluzbeniGlasnik property.
             * 
             * @param value
             *     allowed object is
             *     {@link CTSluzbeniGlasnik }
             *     
             */
            public void setSluzbeniGlasnik(CTSluzbeniGlasnik value) {
                this.sluzbeniGlasnik = value;
            }

        }

    }

}
