//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.08 at 12:02:29 AM CET 
//


package Zahtev.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Primalac">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Organ">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Naziv">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="AdresaOrgana" type="{http://www.ftn.uns.ac.rs/zahtev}CTAdresa"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sadrzaj" type="{http://www.ftn.uns.ac.rs/zahtev}CTSadrzaj"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primalac",
    "sadrzaj"
})
@XmlRootElement(name = "Zahtev", namespace = "http://www.ftn.uns.ac.rs/zahtev")
public class Zahtev {

    @XmlElement(name = "Primalac", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
    protected Zahtev.Primalac primalac;
    @XmlElement(name = "Sadrzaj", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
    protected CTSadrzaj sadrzaj;

    @Override
    public String toString() {
        return "Zahtev {\n" +
                "\tprimalac = " + primalac + ",\n\n" +
                "\tsadrzaj = " + sadrzaj + "\n" +
                "}";
    }

    /**
     * Gets the value of the primalac property.
     * 
     * @return
     *     possible object is
     *     {@link Zahtev.Primalac }
     *     
     */
    public Zahtev.Primalac getPrimalac() {
        return primalac;
    }

    /**
     * Sets the value of the primalac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zahtev.Primalac }
     *     
     */
    public void setPrimalac(Zahtev.Primalac value) {
        this.primalac = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link CTSadrzaj }
     *     
     */
    public CTSadrzaj getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTSadrzaj }
     *     
     */
    public void setSadrzaj(CTSadrzaj value) {
        this.sadrzaj = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Organ">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Naziv">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="AdresaOrgana" type="{http://www.ftn.uns.ac.rs/zahtev}CTAdresa"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organ"
    })
    public static class Primalac {

        @XmlElement(name = "Organ", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
        protected Zahtev.Primalac.Organ organ;


        @Override
        public String toString() {
            return "Primalac {\n" +
                    "\t\torgan = " + organ + "\n" +
                    "\t\t}";
        }

        /**
         * Gets the value of the organ property.
         * 
         * @return
         *     possible object is
         *     {@link Zahtev.Primalac.Organ }
         *     
         */
        public Zahtev.Primalac.Organ getOrgan() {
            return organ;
        }

        /**
         * Sets the value of the organ property.
         * 
         * @param value
         *     allowed object is
         *     {@link Zahtev.Primalac.Organ }
         *     
         */
        public void setOrgan(Zahtev.Primalac.Organ value) {
            this.organ = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Naziv">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="AdresaOrgana" type="{http://www.ftn.uns.ac.rs/zahtev}CTAdresa"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naziv",
            "adresaOrgana"
        })
        public static class Organ {

            @XmlElement(name = "Naziv", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
            protected String naziv;
            @XmlElement(name = "AdresaOrgana", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
            protected CTAdresa adresaOrgana;

            @Override
            public String toString() {
                return "Organ {\n" +
                        "\t\t\tnaziv = " + naziv + ",\n" +
                        "\t\t\tadresaOrgana = " + adresaOrgana + "\n" +
                        "\t\t\t}";
            }

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the adresaOrgana property.
             * 
             * @return
             *     possible object is
             *     {@link CTAdresa }
             *     
             */
            public CTAdresa getAdresaOrgana() {
                return adresaOrgana;
            }

            /**
             * Sets the value of the adresaOrgana property.
             * 
             * @param value
             *     allowed object is
             *     {@link CTAdresa }
             *     
             */
            public void setAdresaOrgana(CTAdresa value) {
                this.adresaOrgana = value;
            }

        }

    }

}
